name: validate changelog [v6]

on:
  pull_request:
    branches:
      - develop

jobs:
  validate-changelog:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/chore/generate-changelog' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: validate changelog entries
        run: node validateChangelog.js
